export const axiosGet = async () => undefined;
export const axiosPost = async () => undefined;
export const axiosPatch = async () => undefined;
export const axiosPut = async () => undefined;
export const axiosDelete = async () => undefined;
export const axiosGetCached = async () => undefined;
export const axiosGetSingle = () => Promise.resolve(undefined);
export const axiosFormData = async () => undefined;
export const GetCancelTokenSource = () => ({ cancel: () => undefined, token: {} });
export const configureInstance = () => undefined;
export const addAuthorizationHeader = () => undefined;
export const clearAxiosCache = () => undefined;
export const createNewInstance = () => undefined;
export const whiteLabelInstance = () => undefined;
export const isSameOriginHost = () => false;
export const baseURL = "";
export const DEF_AXIOS_CACHE_TIMEOUT = 0;
export const axiosCacheSize = () => 0;
export default {};
